name: Generar métricas Puntazo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"  # cada 8 horas

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install dropbox PyGithub

      - name: Generate metrics
        env:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        run: |
          python generar_metricas.py
