name: Procesar videos con FFmpeg

on:
  repository_dispatch:
    types: [procesar_video_ffmpeg]
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    env:
      DROPBOX_APP_KEY:       ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET:    ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

      THIRD_LOGO_ENABLED: ${{ vars.THIRD_LOGO_ENABLED || 'true' }}
      LOGO1_PATH: logos/puntazo.png
      CLUBS_ROOT: clubs
      DEBUG: ${{ vars.DEBUG || 'false' }}

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install dropbox requests

      - name: Instalar FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Ejecutar script de procesamiento
        run: |
          python procesar_videos_ffmpeg.py

