name: Procesar videos con FFmpeg Plus

on:
  workflow_dispatch:
    inputs:
      max_parallel:
        description: "Procesos ffmpeg simultáneos"
        required: false
        default: "2"
      batch_limit:
        description: "Máximo de videos por ejecución"
        required: false
        default: "20"
      threads_per_ffmpeg:
        description: "Hilos por proceso ffmpeg"
        required: false
        default: "2"
      dry_run:
        description: "DRY_RUN (true/false)"
        required: false
        default: "false"

concurrency:
  group: ffmpeg-plus
  cancel-in-progress: false

env:
  # --- Secrets de Dropbox ---
  DROPBOX_APP_KEY:       ${{ secrets.DROPBOX_APP_KEY }}
  DROPBOX_APP_SECRET:    ${{ secrets.DROPBOX_APP_SECRET }}
  DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

  # --- Config que ya usa tu script ---
  THIRD_LOGO_ENABLED: ${{ vars.THIRD_LOGO_ENABLED || 'true' }}
  LOGO1_PATH: logos/puntazo.png
  CLUBS_ROOT: clubs
  DEBUG: ${{ vars.DEBUG || 'false' }}

  # --- Rutas constantes en Dropbox ---
  ENTRANTES: /Puntazo/Entrantes
  DESTINO_RAIZ: /Puntazo/Locaciones

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias y FFmpeg
        run: |
          python -m pip install --upgrade pip
          pip install dropbox requests
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Validar LOGO1_PATH
        run: |
          if [ ! -f "$LOGO1_PATH" ]; then
            echo "❌ No se encontró $LOGO1_PATH (logo de Puntazo)."
            echo "Listado de 'logos/':"; (ls -la logos || true)
            exit 1
          fi

      - name: Ejecutar procesado paralelo (Plus)
        env:
          # Variables desde inputs con fallback a Repository Variables
          MAX_PARALLEL: ${{ github.event.inputs.max_parallel || vars.MAX_PARALLEL || '2' }}
          BATCH_LIMIT: ${{ github.event.inputs.batch_limit || vars.BATCH_LIMIT || '20' }}
          THREADS_PER_FFMPEG: ${{ github.event.inputs.threads_per_ffmpeg || vars.THREADS_PER_FFMPEG || '2' }}
          DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}
        run: |
          echo "⚙️  MAX_PARALLEL=$MAX_PARALLEL  BATCH_LIMIT=$BATCH_LIMIT  THREADS_PER_FFMPEG=$THREADS_PER_FFMPEG  DRY_RUN=$DRY_RUN"
          python procesar_ffmpeg_plus.py
