name: Procesar videos con FFmpeg Plus

on:
  repository_dispatch:
    types: [procesar_video_ffmpeg]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    env:
      # --- Dropbox ---
      DROPBOX_APP_KEY:       ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET:    ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

      # --- Control de marcas/recursos ---
      THIRD_LOGO_ENABLED: ${{ vars.THIRD_LOGO_ENABLED || 'true' }}  # <── AJUSTA AQUÍ EL TERCER LOGO
      LOGO1_PATH: logos/puntazo.png      # <── AJUSTA AQUÍ SI TU RUTA ES OTRA
      CLUBS_ROOT: clubs
      DEBUG: ${{ vars.DEBUG || 'false' }}

    steps:
      - name: Clonar el repositorio (con LFS si aplica)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Mostrar estructura para depuración
        run: |
          echo "Contenido del repo:"
          ls -la
          echo "----"
          echo "Árbol de logos (si existe):"
          (ls -la logos || true)
          (ls -la assets || true)

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias de Python
        run: |
          pip install --upgrade pip
          pip install dropbox requests

      - name: Instalar FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Validar LOGO1_PATH
        run: |
          if [ ! -f "$LOGO1_PATH" ]; then
            echo "❌ No se encontró $LOGO1_PATH (logo de Puntazo)."
            echo "Revisa ruta exacta y mayúsculas/minúsculas."
            echo "Listado de 'logos/':"
            (ls -la logos || true)
            exit 1
          fi

      - name: Ejecutar script de procesamiento (Plus)
        run: |
          python procesar_videos_ffmpeg.py

      - name: Subir artefactos de depuración (si falla)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-debug
          path: |
            ffmpeg*.log
            concat.txt
          if-no-files-found: ignore
