name: Procesar videos con FFmpeg

on:
  repository_dispatch:
    types: [procesar_video_ffmpeg]
  workflow_dispatch:

concurrency:
  group: procesar-videos-ffmpeg
  cancel-in-progress: false

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    env:
      # Dropbox
      DROPBOX_APP_KEY:       ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET:    ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

      # Defaults fijos
      BATCH_LIMIT: "20"
      MAX_PARALLEL: "2"
      THREADS_PER_FFMPEG: "2"
      NEWEST_FIRST: "true"
      DRY_RUN: "false"

      # Rutas estándar
      LOGO1_PATH: logos/logo_borde_bicolor.png
      CLUBS_ROOT: clubs
      ENTRANTES: /Puntazo/Entrantes
      DESTINO_RAIZ: /Puntazo/Locaciones
      THIRD_LOGO_ENABLED: ${{ vars.THIRD_LOGO_ENABLED || 'true' }}
      DEBUG: ${{ vars.DEBUG || 'false' }}

      # Hook por video → dispara “gestionar índice”
      POST_HOOK_PATH: scripts/dispatch_gestionar_indice.py
      POST_HOOK_ALWAYS: "false"
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}

    steps:
      - uses: actions/checkout@v4
        with: { lfs: true }

      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }

      - name: Dependencias y FFmpeg
        run: |
          python -m pip install --upgrade pip
          pip install dropbox requests
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Validar LOGO1_PATH
        run: |
          [ -f "$LOGO1_PATH" ] || { echo "❌ Falta $LOGO1_PATH"; exit 1; }

      - name: Procesar (20, 2×2, newest, sin dry-run)
        run: |
          python procesar_videos_ffmpeg.py
