name: Procesar videos con FFmpeg

on:
  repository_dispatch:
    types: [procesar_video_ffmpeg]
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Python y dependencias
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías necesarias
        run: pip install dropbox requests

      - name: Instalar FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Ejecutar el script de procesamiento
        env:
          DROPBOX_APP_KEY:       ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET:    ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        run: python procesar_videos_ffmpeg.py
