name: Procesar videos con FFmpeg Plus

on:
  repository_dispatch:
    types: [procesar_video_ffmpeg_plus]
  workflow_dispatch:

# Evita ejecuciones paralelas: nuevas ejecuciones esperan a que termine la anterior
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    env:
      # --- Dropbox (usa tus secrets existentes) ---
      DROPBOX_APP_KEY:       ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET:    ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

      # --- Control de marcas/recursos ---
      THIRD_LOGO_ENABLED: ${{ vars.THIRD_LOGO_ENABLED || 'false' }}
      LOGO1_PATH: assets/logos/puntazo.png
      CLUBS_ROOT: clubs
      DEBUG: ${{ vars.DEBUG || 'false' }}

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias de Python
        run: |
          pip install --upgrade pip
          pip install dropbox requests

      - name: Instalar FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Validar LOGO1_PATH
        run: |
          if [ ! -f "$LOGO1_PATH" ]; then
            echo "❌ No se encontró $LOGO1_PATH (logo de Puntazo)."
            exit 1
          fi

      - name: Ejecutar script de procesamiento (Plus)
        run: |
          python procesar_videos_ffmpeg_plus.py

      - name: Subir artefactos de depuración (si falla)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-debug
          path: |
            ffmpeg*.log
            concat.txt
          if-no-files-found: ignore
