name: Supervisor Puntazo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: supervisor-puntazo
  cancel-in-progress: true

jobs:
  supervise:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Tick loop
        run: |
          echo "⏱️ Iniciando supervisor de prueba..."
          for i in {1..5}; do
            echo "Tick $i at $(date -u)"
            sleep 60
          done
          echo "✅ Supervisor de prueba terminado"
